# Generated by Django 2.2.6 on 2019-11-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_year', models.IntegerField()),
                ('launch_date', models.DateField()),
                ('rocket_name', models.CharField(max_length=100)),
                ('land_success', models.BooleanField()),
                ('nationality', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('launch_success', models.BooleanField()),
            ],
        ),
    ]
