# Generated by Django 2.2.7 on 2019-11-12 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0003_auto_20191112_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launch',
            name='flight_id',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='landing_intent',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='landing_type',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='landing_vehicle',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='orbit',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='start_end',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='tbd',
        ),
    ]
