version: "3.2"
services:
  backend:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend/spacex
    volumes:
      - ./frontend:/spacex
      # One-way volume to use node_modules from inside image
      - ./frontend:/spacex/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm start